In [ ]:
# # 🔹 기본 실습 1: Numpy 배열 생성 및 슬라이싱
# # 문제:
# #
# # 2차원 Numpy 배열 3x3 을 생성하고,
# # 특정 행과 열을 슬라이싱하여 출력하세요.
# # - 첫 번째 행 가져오기
# # - 2번째 열만 가져오기
# # - 1행 1열~끝까지

In [12]:
import numpy as np
import pandas as pd
arr = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(arr[0])
print(arr[:,1])
print(arr[1:,1:])




A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start(

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.




A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start(

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.




A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start(

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\it\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start(

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



[1 2 3]
[2 5 8]
[[5 6]
 [8 9]]


In [ ]:
# 🔹 기본 실습 2: 배열 연산
# 문제:
# 두 개의 Numpy 배열을 생성하고,
# 더하기(+), 빼기(-), 곱하기(*), 나누기(/) 연산을 수행하세요.
# [1, 2, 3]
# [4, 5, 6]

# 배열 생성
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 배열 연산
print("더하기:", arr1 + arr2)  # [5 7 9]
print("빼기:", arr1 - arr2)    # [-3 -3 -3]
print("곱하기:", arr1 * arr2)  # [4 10 18]
print("나누기:", arr1 / arr2)  # [0.25 0.4  0.5 ]


In [4]:
# 🔹 기본 실습 3: 리스트를 Numpy 배열로 변환
# 문제:
# 리스트 데이터를 Numpy 배열로 변환하고, 배열의 데이터 타입을 출력하세요.
# list_data = [10, 20, 30, 40, 50]
# 리스트 생성
list_data = [10, 20, 30, 40, 50]

# 리스트를 Numpy 배열로 변환
np_array = np.array(list_data)

# 데이터 타입 출력
print("변환된 Numpy 배열:", np_array)
print("배열 데이터 타입:", np_array.dtype)

변환된 Numpy 배열: [10 20 30 40 50]
배열 데이터 타입: int64


In [5]:
# 🔹 응용 실습 1: 영화 평점 데이터 불러오기 및 처음 5행 출력
#
# 문제:
# CSV 파일에서 영화 평점 데이터를 불러오고, 처음 5행만 출력하세요.
ratings= np.loadtxt("mini_ratings.csv", delimiter=",",
           skiprows=1)
print(ratings[:5])

[[ 3.   6.   3.7]
 [ 5.  10.   3.1]
 [ 3.   2.   2.7]
 [ 1.   9.   1.7]
 [ 3.   8.   2.4]]


In [7]:
# 🔹 응용 실습 2: 영화 평점의 전체 평균 계산
#
# 문제:
# 불러온 영화 평점 데이터에서 전체 평균 평점을 계산하세요.

ratings_only = ratings[:,2]
print(ratings_only)
print(f"전체 영화의 평균 : {np.mean(ratings_only)}")


[3.7 3.1 2.7 1.7 2.4 3.2 3.5 3.1 3.4 3.1 5.  3.6 3.9 1.  3.3 1.8 1.7 4.7
 3.4 3.2]
전체 영화의 평균 : 3.075


In [13]:
# 🔹 응용 실습 3: 사용자별 평균 평점 계산 및 CSV 저장
# 문제:
#
# 사용자 ID별 평균 평점을 계산하고
# 사용자만 추출,
user_ids = ratings[:,0]
# 점수만 추출
ratings_only = ratings[:,2]
# 중복 사용자 분리
unique_users = np.unique(user_ids)
print(unique_users) # 1,2,3,4,5
#사용자별, 평균 평점 계산,
user_avg_ratings = {
    # ratings_only[user_ids == user] : 전체 유저 중에서, 중복 제거한 한 유저만 검색
    user : np.mean(ratings_only[user_ids == user])
    for user in unique_users
}
print(user_avg_ratings)

# 이를 CSV 파일로 저장하세요.
# 데이터프레임 생성 및 CSV 저장
df = pd.DataFrame(list(user_avg_ratings.items()), columns=["UserID", "AverageRating"])
df.to_csv("user_avg_ratings.csv", index=False)



[1. 2. 3. 4. 5.]
{np.float64(1.0): np.float64(2.3), np.float64(2.0): np.float64(3.533333333333333), np.float64(3.0): np.float64(3.1142857142857143), np.float64(4.0): np.float64(3.3666666666666667), np.float64(5.0): np.float64(3.266666666666666)}
